APPLICATION_PORT: 8083

POSTGRES_USER: postgresql
POSTGRES_PASS: postgresql
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DB_NAME: learning_reactive_r2dbc

MONGO_USER: mongodb
MONGO_PASS: mongodb
MONGO_HOST: 127.0.0.1:27017
MONGO_DB_NAME: learning_reactive_mongo

REDIS_HOST: localhost
REDIS_PORT: 6379

KAFKA_HOST: localhost:9092
KAFKA_SECURITY_PROTOCOL: PLAINTEXT